import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ea2804',
        'primary-deep': '#c01f00',
        'on-primary': '#ffffff',
        ink: '#202020',
        body: '#3a3a3a',
        charcoal: '#575757',
        mute: '#646464',
        ash: '#8d8d8d',
        stone: '#bbbbbb',
        'on-dark': '#fcfcfc',
        'on-dark-mute': 'rgba(252,252,252,0.72)',
        canvas: '#f9f7f3',
        'surface-bone': '#f3f0e8',
        'surface-card': '#ffffff',
        'surface-dark': '#202020',
        'surface-deep': '#000000',
        hairline: 'rgba(32,32,32,0.10)',
        'hairline-strong': 'rgba(32,32,32,0.22)',
        'divider-dark': 'rgba(255,255,255,0.2)',
        'badge-success': '#2b9a66',
        gold: '#d4a24e',
      },
      fontFamily: {
        display: ['"Bricolage Grotesque"', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        arab: ['Amiri', '"Noto Naskh Arabic"', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '10px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '32px',
        full: '9999px',
      },
      boxShadow: {
        'drop-soft': '0 8px 24px rgba(32,32,32,0.08)',
        'drop-card': '0 2px 8px rgba(32,32,32,0.05)',
        'drop-lifted': '0 4px 16px rgba(32,32,32,0.10), 0 1px 4px rgba(32,32,32,0.06)',
        'nav-float': '0 -1px 0 0 rgba(0,0,0,0.04), 0 20px 48px -8px rgba(0,0,0,0.14)',
        'glow-primary': '0 4px 20px rgba(234,40,4,0.30)',
        'glow-gold': '0 4px 20px rgba(212,162,78,0.25)',
      },
      maxWidth: {
        app: '460px',
        content: '1280px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        xxxl: '48px',
        section: '96px',
        band: '160px',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(1)', opacity: '0.6' },
          '100%': { transform: 'scale(1.6)', opacity: '0' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'shimmer-sweep': {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.4s ease-out both',
        'fade-in': 'fade-in 0.3s ease-out both',
        'scale-in': 'scale-in 0.35s ease-out both',
        'pulse-ring': 'pulse-ring 1.4s ease-out infinite',
        'slide-up': 'slide-up 0.55s cubic-bezier(0.16,1,0.3,1) both',
        'shimmer-sweep': 'shimmer-sweep 2.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
